### PR TITLE
add instruction to run jobs in other namespace

### PR DESCRIPTION
**Pull request by showuon**
1. Provide example `flink` service account yaml file
2. Provide instruction to run flink jobs on other namespace

### CODE REVIEW

**Comment by kornys** [comment]
It wont work, you removed finalizers rights which are needed on ocp.

**Comment by kornys** [comment]
Also i miss rights to read secrets to use connection info for kafka connecting

**Review by kornys — CHANGES_REQUESTED** [review]
Please review my comments.

**Comment by showuon** [comment]
Thanks for the comment, @kornys ! It makes sense we should add finalizer and secret permissions. PR updated. Thanks.

**Comment by kornys** [comment]
> Thanks for the comment, @kornys ! It makes sense we should add finalizer and secret permissions. PR updated. Thanks.

@showuon just out of curiosity why do you do not use same example as I added to jira issue which I sent you?

**Comment by showuon** [comment]
> > Thanks for the comment, @kornys ! It makes sense we should add finalizer and secret permissions. PR updated. Thanks.
> 
> @showuon just out of curiosity why don't you use same example as I added to jira issue which I sent you?
> 
> because I miss pods/finalizers and also secrets should be just get,list not all rights.

Thanks for the comment. PR updated!

**Review by kornys — APPROVED** [review]

**Pull request merged**
